### ISSUE TITLE
Joining Teensy support

### ISSUE THREAD

**Issue by Traumflug** [Traumflug/Teacup_Firmware#42]
DaveX aka. drf aka. drf5n has uploaded his branch for the Teensy 3.0: http://forums.reprap.org/read.php?146,195325,199577#msg-199577 Great work!

I had a look into this and see a lot of commits duplicating commits already on the master branch. These could vanish by rebasing this branch to more recent commits of the master, or even Gen7 branch. Rebasing would also allow a better overview of what actually makes the Teensy support.

Are you fine with me doing this rebasing, David? The code at the top of the teensy3 branch wouldn't change, but before pushing, you'd have to follow upstream first, like:

```
git pull
```

in case you're already on the teensy3 branch, or

```
git pull
git checkout teensy3
git rebase origin/teensy3
```

in case you were elsewhere. If you have different ideas, I'm all open. :)

**Comment by Traumflug** [comment]
@drf5n, do you still know how you compiled this thing? With which Arduino version? There's a user asking in the RepRap forum: http://forums.reprap.org/read.php?147,469915

He gets errors on lines containing "BSS".

I just checked out the teensy3 branch and tried to compile, but don't get far:

    $ make -f Makefile-teensy3 
      CC        build/usb_dev.o
    usb_dev.c:3:23: fatal error: mk20dx128.h: No such file or directory

**Comment by michaeljball** [comment]
Thank you Traumflug.   The mk20dx128.h  ( or mk20dx256.h ) is part of the Arduino Teensy extension.  Compiling from within the Arduino IDE (yeah... I know...) provides this...
Any help appreciated.

**Comment by Traumflug** [comment]
Now, did you swap to Arduino IDE 1.5?

**Comment by Traumflug** [comment]
Also, installing Git is a good idea:

    sudo apt-get install git gitk
    git clone https://github.com/Traumflug/Teacup_Firmware.git

Then you can swap between branches in a snap. Like

    git checkout <branchname>

And fetch updates like

    git pull

Much easier than downloading and unpacking tarballs.

**Comment by michaeljball** [comment]
<shameful admission> I have Git installed, just not very good at the command line... I know... I know... </shameful admission>

**Comment by michaeljball** [comment]
Downloading Arduino 1.5.8.  will install Teensyduino extensions and try recompiling.

**Comment by michaeljball** [comment]
Sorry... The Teensy3.1 Developer has stated that they do not yet support Arduino 1.5.x, but are working on a port for 1.6.x currently.  

https://forum.pjrc.com/threads/27740-Arduino-1-6-0-any-plans-to-support-it?p=64407&viewfull=1#post64407

**Comment by Traumflug** [comment]
I take this 1.5 recommendation back. Teensyduino package apparently comes with a comiler, see Forum discussion.

**Comment by michaeljball** [comment]
Are there any tricks I need to be aware of to get USB serial showing up on the Teensy 3.1?
It compiles now error free (thank you again!) but I know Paul had mentioned elsewhere that the serial interface doesn't register until first use... 
I'm at a stand still at the moment.  Everything "appears" proper.  If I compile and upload a different app to the Teensy, I have USB Serial, but not so much with Teacup_Firmware.. 

I'm using the Teensy3.1 branch with Paul's latest Teensyduino as per instructions here.   The Makefile does have:  "CFLAGS += -DUSB_SERIAL"   as enabled from the repo... As I said... not sure where to look or how to debug.

Thoughts? 
Thank you in advance.

**Comment by Traumflug** [comment]
I've just rebased the teensy3 branch to master, so you get the newer goodies. Let's cross fingers it still compiles. :-)

**Comment by michaeljball** [comment]
"I've just rebased the teensy3 branch to master, so you get the newer goodies. Let's cross fingers it still compiles. :-)" 
Teensy3 branch?  Or the Teensy3.1 branch?  The former compiled but does not function.  The latter is fully functional.

**Comment by Traumflug** [comment]
> Teensy3 branch? Or the Teensy3.1 branch?

It's the teensy3 branch, without .1. This branch is the one which got a commit recently, so I assumed this is the currently working one.

Fine to see teensy3.1 working, but it's now some 200 commits behind. For example, no adaptive homing feedrates, no CoreXY support. Rebasing is no rocket science if done commit by commit, like

```
git checkout teensy3.1
git rebase experimental~500
git rebase experimental~499
git rebase experimental~498
...
```
Can also be done in bigger steps if you're brave. Compiling and trying occasionally is a good idea. You always have the origin/teensy3.1 branch as backup.

Probably you noticed, all this ARM stuff is a bit messier than AVR. There is no MCU support (no -mmcu) in arm-gcc and no hardware support (register definitions) in arm-libc. It's nice that what we currently have it working on the Teensy, but it's a solution which works only there. Nowadays we also have the Arduino Due, the Gen7-ARM and quite a number of other ARM based controllers.

I've put some research into finding a solution which works for all these MCUs. Two of them are on the gen7-arm branch (each of the two commits there), just a proof of concept. The second commit uses MBED as a subrepository, but then I was notified the MCU of the Arduino Due isn't in MBED. Code in MBED is also somewhat wasteful with resources, a simple Hello World for the serial line builds to > 8 kB.

The solution I'm currently seeking for is to collect the neccessary files from CMSIS (sort of a sub-part of MBED) and *copy* them into the Teacup repo. This allows to also collect files from vendors not in MBED, e.g. the Arduino Due. This is what the first commit on the gen7-arm branch does. It's not too complicated and once the base works, the other neccessary solutions are already on these two teensy3 branches.

If you want to put some work into there: greatly appreciated. For myself I'll work on this Configtool milestone first, because that's what I consider to be the biggest bottleneck for attracting new users. Then I hope to finally find the time to get this Gen7-ARM running with the strategy described above. The board sits on my desk and has collected quite a bit of dust already :-)

**Comment by michaeljball** [comment]
Thank you for your time in all of this.  I'm fairly familiar with MBED and CMSIS hardware abstraction.  It is very likely the right way to go.  As for the Due not being in MBED... That's a travesty. (Merely by number of Due boards purchased, I do not have one)   However... 
You might want to look at platformio.org   They have pulled together a cross-platform compiler framework and library dependency resolver that includes over 100 boards... including the Arduino Due.  I did a writeup on PlatformIO [here](http://arduino-pi.blogspot.ca/2015/04/platformio-cross-platform-code-builder.html).

I'm currently being tasked to get a GCODE firmware running on Freescale's FRDM-K64F development board, so I won't be back on the Teensy for a few weeks. 

I'll look at what's involved in updating the 3.1 branch at that time. 

Thanks again.

**Comment by Traumflug** [comment]
> You might want to look at platformio.org

Looks like a good collection of tools. Had a look at the various blink examples and each uses different code, so apparently no hardware abstraction. Certainly worth a look when we get into trouble with the tools available/findable, though.

Configtool works nicely for building and uploading. AVR-only, so far, but nothing stopping ARM support. Whatever can be put into a script can also be run by Configtool. Configure, build, upload from one place. Perhaps even printer calibration in some nice future.

> I'm currently being tasked to get a GCODE firmware running on Freescale's FRDM-K64F development board, so I won't be back on the Teensy for a few weeks.

Not Teacup? D'oh. :-)

**Comment by michaeljball** [comment]
Configtool IS looking pretty nice.  Congrats, and good luck.  :)

As far as Teacup on the Freescale board... They want me using the Kinetis Design Studio with Processor Expert and the SDK.  

I'll admit that when you're used to cutting and pasting a few lines of code per pin/function, going back to a visual tool is a bit of a challenge.   LOL
