### ISSUE TITLE
Compile Issues for Teensy 3.1

### ISSUE THREAD

**Issue by nikkiverre** [Traumflug/Teacup_Firmware#93]
Hi,

I am trying to compile Teacup for Teensy3. I am following the Developer's instructions from http://reprap.org/wiki/Teacup_Firmware#Developer_Installation

Here are the errors I am getting

![screenshot from 2014-07-09 12 40 30](https://cloud.githubusercontent.com/assets/7884384/3530340/8ee951a0-07a3-11e4-897f-c3b8bc5f9748.png)

![screenshot from 2014-07-09 12 41 43](https://cloud.githubusercontent.com/assets/7884384/3530359/a76664c0-07a3-11e4-82a5-ef300ac84169.png)

I am not sure if I am missing something...

Thanks for your time!

Nikki

**Comment by michaeljball** [comment]
Re-asking Nikki's question... do I work on the teensy3.1-refactor branch now?
still get this error on compile:  (fresh clean install of Arduino 1.0.6 /Teensyduino)
gcode_parse.c:29: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'read_digit'
gcode_parse.c:32: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'next_target'
gcode_parse.c: In function 'gcode_parse_char':
gcode_parse.c:114: error: 'read_digit' undeclared (first use in this function)
gcode_parse.c:114:22: note: each undeclared identifier is reported only once for each function it appears in

**Comment by Traumflug** [comment]
The refactoring branch id for, well, refactoring. Like aligning Nikki's work in a fashion which doesn't break support for ATmegas. Newer considerations came to the conclusion there is no point in relying on this Teensy support package. There are so many ARMs now, making it impossible to fit them all into this package. Instead, there is the ARM (ARM, the company) supported MBED, which in turn comes with CMSIS. CMSIS is low level enough and supports virtually all ARM chips.

But that's not important now, for your purposes teensy3.1 and teensy3.1-refactor should have the same code.

I see these two lines erroring contain "BSS". It's be interesting to what this macro gets expanded. Arduino IDE compiles into /tmp/build... Can you find a file gcode_parse.i file in there? That's the macro-expanded source code. A bit difficult to read, but you should find "read_digit" in there.

It might work to simply remove this BSS. It's only a binary size optimisation.

**Comment by Traumflug** [comment]
There's a gen7-arm branch which brings in a proof of concept on how to build with MBED/CMSIS in a fashion which should work for all ARM variants in the retarget-sample-code folder.
